# Generated by Django 4.1.1 on 2022-10-03 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsList',
            new_name='Product',
        ),
    ]
